- name: Configure Join Commands on Master Node
  hosts: master
  become: yes
  tasks:
    - name: Retrieve Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Worker Nodes
  hosts: workers
  become: yes
  
  vars:
    USER: ubuntu
    IP_MASTER: 10.150.192.100

  tasks:
    - name: Enable TCP port 6443 (On Master) is able to connect from Worker
      wait_for: "host={{ IP_MASTER }} port=6443 timeout=1"

    - name: Join worker to cluster
      shell: "{{ hostvars['{{ IP_MASTER }}'].join_command }} >> node_joined.log"
      args:
        chdir: "/home/{{ USER }}"
        creates: node_joined.log